// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML;
using System.Collections.Generic;

namespace Text_Classification_Sample_1ML.Model
{
    public class ConsumeModel
    {
        // For more info on consuming ML.NET models, visit https://aka.ms/model-builder-consume
        // Method for consuming model in your app
        public static Dictionary<string, float> Predict(ModelInput input)
        {
            // Create new MLContext
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine
            string modelPath = @"C:\Users\LeapDev Developer\AppData\Local\Temp\MLVSTools\Text Classification Sample 1ML\Text Classification Sample 1ML.Model\MLModel.zip";
            ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            // Use model to make prediction on input data
            ModelOutput result = predEngine.Predict(input);

            return result.ToDictionary(predEngine.OutputSchema, "label");
        }
    }
}
