// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Text_Classification_Sample_1ML.Model
{
    public class ModelInput
    {
        [ColumnName("label"), LoadColumn(0)]
        public string Label { get; set; }


        [ColumnName("content"), LoadColumn(1)]
        public string Content { get; set; }


    }
}
